services:
  lanoscertifiedstore.presentation:
    image: ${DOCKER_REGISTRY-}lanoscertifiedstorepresentation
    build:
      context: .
      dockerfile: src/LanosCertifiedStore.Presentation/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      lanoscertifiedstore.database:
        condition: service_healthy
        restart: true
  
  lanoscertifiedstore.database:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: lsc_db
    environment:
      - POSTGRES_DB=LanosCertifiedStore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/lsc_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  lanoscertifiedstore.identity:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: lsc_identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/localhost_cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/localhost_key.pem
      - API_REGISTRATION_MESSAGE_ENDPOINT=https://host.docker.internal:5001/api/identity
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/keycloak/realms/lsc-realm-export.json:/opt/keycloak/data/import/realm.json
      - ./.files/keycloak/themes/lsc-theme.jar:/opt/keycloak/providers/lsc-theme.jar
      - ./.files/keycloak/validators/unique-attribute-validator.jar:/opt/keycloak/providers/unique-attribute-validator.jar
      - ./.files/keycloak/listeners/custom-event-listener.jar:/opt/keycloak/providers/custom-event-listener.jar
      - ./.certs:/opt/keycloak/certs
    ports:
      - "18080:8080"
      - "8843:8443"
      - "9000:9000"
    healthcheck:
      test: [
        "CMD-SHELL",
        "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: 
        http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; 
        then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lanoscertifiedstore.seq:
    image: datalust/seq:latest
    container_name: lsc_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"