using Domain.Entities.VehicleRelated.LocationRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.LocationRelated.LocationRegionRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleLocationRegionSortingSettings : BaseSortingSettings<VehicleLocationRegion>;