using Persistence.DataModels.VehicleRelated.LocationRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.LocationRelated.LocationRegionRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleLocationRegionSortingSettings : BaseSortingSettings<VehicleLocationRegionDataModel>;