using LanosCertifiedStore.Application.Shared.RequestParamsRelated;
using LanosCertifiedStore.Domain.Entities.VehicleRelated.TypeRelated;

namespace LanosCertifiedStore.Application.VehicleBodyTypes;

public sealed class VehicleBodyTypeFilteringRequestParameters : BaseFilteringRequestParameters<VehicleBodyType>;