using LanosCertifiedStore.Application.Shared.RequestRelated;

namespace LanosCertifiedStore.Application.Identity.Commands.ResetPasswordCommandRequestRelated;

public sealed record ResetPasswordCommandRequest : ICommandRequest;