using Persistence.DataModels.VehicleRelated.LocationRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.LocationRelated.LocationAreaRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleLocationAreaSortingSettings : BaseSortingSettings<VehicleLocationAreaDataModel>;