using Persistence.Entities.VehicleRelated.TypeRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.TypeRelated.VehicleTransmissionTypeRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleTransmissionTypeSortingSettings : BaseSortingSettings<VehicleTransmissionTypeEntity>;