using LanosCertifiedStore.Application.Shared.RequestParamsRelated;
using LanosCertifiedStore.Domain.Entities.VehicleRelated.TypeRelated;

namespace LanosCertifiedStore.Application.VehicleTransmissionTypes;

public sealed class VehicleTransmissionTypeFilteringRequestParameters : 
    BaseFilteringRequestParameters<VehicleTransmissionType>;