using LanosCertifiedStore.Application.Shared.RequestParamsRelated;
using LanosCertifiedStore.Domain.Entities.VehicleRelated.TypeRelated;

namespace LanosCertifiedStore.Application.VehicleEngineTypes;

public sealed class VehicleEngineTypeFilteringRequestParameters : BaseFilteringRequestParameters<VehicleEngineType>;