using Persistence.DataModels.VehicleRelated.TypeRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.TypeRelated.VehicleDrivetrainTypeRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleDrivetrainTypeSortingSettings : BaseSortingSettings<VehicleDrivetrainTypeDataModel>;