using Persistence.Entities.VehicleRelated.LocationRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.LocationRelated.LocationTownRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleLocationTownSortingSettings : BaseSortingSettings<VehicleLocationTownEntity>;