using Application.RequestParameters.Common.Classes;
using Domain.Entities.VehicleRelated.LocationRelated;

namespace Application.RequestParameters.LocationRelated;

public sealed class VehicleLocationTownFilteringRequestParameters : BaseFilteringRequestParameters<VehicleLocationTown>;