using LanosCertifiedStore.Domain.Entities.VehicleRelated;

namespace LanosCertifiedStore.Persistence.SeedingData;

internal static class SeedImages
{
    public static List<VehicleImage> GetImages(List<Vehicle> vehicles) =>
    [
        // Toyota Camry 2022 Sedan Black +
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/ihacdayw1bqd6a2l3qfy",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/ihacdayw1bqd6a2l3qfy.jpg",
            true),
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/uq0xnujgnf05icg06yok",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/uq0xnujgnf05icg06yok.jpg",
            false),
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/sz6xxhsxfvtd5knk64ef",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/sz6xxhsxfvtd5knk64ef.jpg",
            false),
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/zvmvv4jkt38kdxgx8u2r",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/zvmvv4jkt38kdxgx8u2r.jpg",
            false),
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/hfqhrda1bozqqntx5dtw",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/hfqhrda1bozqqntx5dtw.jpg",
            false),
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/edoolr2dz9rmgome7l7a",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/edoolr2dz9rmgome7l7a.jpg",
            false),
        new(
            vehicles[0].Id,
            (string)"LanosCertifiedStore/Vehicles/wlah9lb5bzmm6rau6ex3",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708506203/LanosCertifiedStore/Vehicles/wlah9lb5bzmm6rau6ex3.jpg",
            false),
        // Ford F-150 White +
        new(
            vehicles[1].Id,
            (string)"LanosCertifiedStore/Vehicles/yhe9l7wpj1wx7i72ofck",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708509097/LanosCertifiedStore/Vehicles/yhe9l7wpj1wx7i72ofck.jpg",
            true),
        new(
            vehicles[1].Id,
            (string)"LanosCertifiedStore/Vehicles/fn1jxpwnedcrklfmbr0m",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708509097/LanosCertifiedStore/Vehicles/fn1jxpwnedcrklfmbr0m.jpg",
            false),
        new(
            vehicles[1].Id,
            (string)"LanosCertifiedStore/Vehicles/tupleibcum9zvcowbsf6",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708509097/LanosCertifiedStore/Vehicles/tupleibcum9zvcowbsf6.jpg",
            false),
        new(
            vehicles[1].Id,
            (string)"LanosCertifiedStore/Vehicles/umekdzskvzkq8mqd3j3r",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708509098/LanosCertifiedStore/Vehicles/umekdzskvzkq8mqd3j3r.jpg",
            false),
        // Honda Civic Coupe 2019 Yellow +
        new(
            vehicles[2].Id,
            (string)"LanosCertifiedStore/Vehicles/unvudoxhcupxoj8ry7tt",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708513095/LanosCertifiedStore/Vehicles/unvudoxhcupxoj8ry7tt.jpg",
            true),
        new(
            vehicles[2].Id,
            (string)"LanosCertifiedStore/Vehicles/sqep0bdjhgiogm5sqizp",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708513095/LanosCertifiedStore/Vehicles/sqep0bdjhgiogm5sqizp.jpg",
            false),
        new(
            vehicles[2].Id,
            (string)"LanosCertifiedStore/Vehicles/bvim7nrb5oyc7ybjh3yw",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708513095/LanosCertifiedStore/Vehicles/bvim7nrb5oyc7ybjh3yw.jpg",
            false),
        new(
            vehicles[2].Id,
            (string)"LanosCertifiedStore/Vehicles/sry8itc3nxialvvzlwbd",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708513095/LanosCertifiedStore/Vehicles/sry8itc3nxialvvzlwbd.jpg",
            false),
        new(
            vehicles[2].Id,
            (string)"LanosCertifiedStore/Vehicles/w6xo7tgygzm9rtbefchp",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708513095/LanosCertifiedStore/Vehicles/w6xo7tgygzm9rtbefchp.jpg",
            false),
        new(
            vehicles[2].Id,
            (string)"LanosCertifiedStore/Vehicles/yy7nl6grfobgnpnt2zd7",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708513095/LanosCertifiedStore/Vehicles/yy7nl6grfobgnpnt2zd7.jpg",
            false),
        // Chevrolet Silverado Pickup Blue +
        new(
            vehicles[3].Id,
            (string)"LanosCertifiedStore/Vehicles/ccrwy8hotzpdvccf3fno",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708514798/LanosCertifiedStore/Vehicles/ccrwy8hotzpdvccf3fno.jpg",
            true),
        new(
            vehicles[3].Id,
            (string)"LanosCertifiedStore/Vehicles/rk3lynlrctegvft60mxv",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708514798/LanosCertifiedStore/Vehicles/rk3lynlrctegvft60mxv.jpg",
            false),
        new(
            vehicles[3].Id,
            (string)"LanosCertifiedStore/Vehicles/zby9kpoy92aw6trjpxuh",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708514798/LanosCertifiedStore/Vehicles/zby9kpoy92aw6trjpxuh.jpg",
            false),
        new(
            vehicles[3].Id,
            (string)"LanosCertifiedStore/Vehicles/oci6v5p1djtydbbra0tr",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708514798/LanosCertifiedStore/Vehicles/oci6v5p1djtydbbra0tr.jpg",
            false),
        // Chevrolet Silverado Pickup White +
        new(
            vehicles[4].Id,
            (string)"LanosCertifiedStore/Vehicles/bqljigfas3dwuo75bbi9",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516378/LanosCertifiedStore/Vehicles/bqljigfas3dwuo75bbi9.jpg",
            true),
        new(
            vehicles[4].Id,
            (string)"LanosCertifiedStore/Vehicles/q2kngdxmcuvlkjvgah22",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516378/LanosCertifiedStore/Vehicles/q2kngdxmcuvlkjvgah22.jpg",
            false),
        new(
            vehicles[4].Id,
            (string)"LanosCertifiedStore/Vehicles/uigyevsaml3swl6arihu",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516378/LanosCertifiedStore/Vehicles/uigyevsaml3swl6arihu.jpg",
            false),
        new(
            vehicles[4].Id,
            (string)"LanosCertifiedStore/Vehicles/cutifvagaifbygvcwmk4",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516378/LanosCertifiedStore/Vehicles/cutifvagaifbygvcwmk4.jpg",
            false),
        // Volkswagen Passat Wagon Black +
        new(
            vehicles[5].Id,
            (string)"LanosCertifiedStore/Vehicles/csqdmqvaarhnxh4ne8y6",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516950/LanosCertifiedStore/Vehicles/csqdmqvaarhnxh4ne8y6.jpg",
            true),
        new(
            vehicles[5].Id,
            (string)"LanosCertifiedStore/Vehicles/f9mmqlllnc5cc0zudiqb",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516950/LanosCertifiedStore/Vehicles/f9mmqlllnc5cc0zudiqb.jpg",
            false),
        new(
            vehicles[5].Id,
            (string)"LanosCertifiedStore/Vehicles/f2hcnbijkhhddn7fbrak",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516950/LanosCertifiedStore/Vehicles/f2hcnbijkhhddn7fbrak.jpg",
            false),
        new(
            vehicles[5].Id,
            (string)"LanosCertifiedStore/Vehicles/m75dnuovojhhtu1lnqd4",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516950/LanosCertifiedStore/Vehicles/m75dnuovojhhtu1lnqd4.jpg",
            false),
        new(
            vehicles[5].Id,
            (string)"LanosCertifiedStore/Vehicles/utyrwzl2tgrctmlzbwll",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516950/LanosCertifiedStore/Vehicles/utyrwzl2tgrctmlzbwll.jpg",
            false),
        new(
            vehicles[5].Id,
            (string)"LanosCertifiedStore/Vehicles/mpvkmtu5qtgwid0gtlex",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708516950/LanosCertifiedStore/Vehicles/mpvkmtu5qtgwid0gtlex.jpg",
            false),
        // Volkswagen Passat Sedan Gray
        new(
            vehicles[6].Id,
            (string)"LanosCertifiedStore/Vehicles/qgl0bsb0wanjd96yzssn",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708517723/LanosCertifiedStore/Vehicles/qgl0bsb0wanjd96yzssn.jpg",
            true),
        new(
            vehicles[6].Id,
            (string)"LanosCertifiedStore/Vehicles/ejvibyhyh0xpgzupzazp",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708517722/LanosCertifiedStore/Vehicles/ejvibyhyh0xpgzupzazp.jpg",
            false),
        new(
            vehicles[6].Id,
            (string)"LanosCertifiedStore/Vehicles/egn3swvuosq3le2tqyrx",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708517722/LanosCertifiedStore/Vehicles/egn3swvuosq3le2tqyrx.jpg",
            false),
        new(
            vehicles[6].Id,
            (string)"LanosCertifiedStore/Vehicles/cmdgfj6u9gw44mpxxss2",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708517722/LanosCertifiedStore/Vehicles/cmdgfj6u9gw44mpxxss2.jpg",
            false),
        new(
            vehicles[6].Id,
            (string)"LanosCertifiedStore/Vehicles/b4owvdwes7wtzqn4jw4s",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708517722/LanosCertifiedStore/Vehicles/b4owvdwes7wtzqn4jw4s.jpg",
            false),
        // Nissan Altima Sedan Red
        new(
            vehicles[7].Id,
            (string)"LanosCertifiedStore/Vehicles/mi0invd8xlo2kv3tcqdg",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708525216/LanosCertifiedStore/Vehicles/mi0invd8xlo2kv3tcqdg.jpg",
            true),
        new(
            vehicles[7].Id,
            (string)"LanosCertifiedStore/Vehicles/aroxeevxprqactzhkcnz",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708525216/LanosCertifiedStore/Vehicles/aroxeevxprqactzhkcnz.jpg",
            false),
        new(
            vehicles[7].Id,
            (string)"LanosCertifiedStore/Vehicles/phceqqrqed9z2zfsbkbb",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708525216/LanosCertifiedStore/Vehicles/phceqqrqed9z2zfsbkbb.jpg",
            false),
        // BMW M3 Sedan White
        new(
            vehicles[8].Id,
            (string)"LanosCertifiedStore/Vehicles/glmsconrhhm4oqfls07g",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708526290/LanosCertifiedStore/Vehicles/glmsconrhhm4oqfls07g.jpg",
            true),
        new(
            vehicles[8].Id,
            (string)"LanosCertifiedStore/Vehicles/aku6xzbt8tlztqjujlan",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708526290/LanosCertifiedStore/Vehicles/aku6xzbt8tlztqjujlan.jpg",
            false),
        new(
            vehicles[8].Id,
            (string)"LanosCertifiedStore/Vehicles/eudgxg6qzrggbzetb5cd",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708526289/LanosCertifiedStore/Vehicles/eudgxg6qzrggbzetb5cd.jpg",
            false),
        new(
            vehicles[8].Id,
            (string)"LanosCertifiedStore/Vehicles/lmyg4pmrw2aims4purnk",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708526290/LanosCertifiedStore/Vehicles/lmyg4pmrw2aims4purnk.jpg",
            false),
        // Mercedes-Benz C-Class Sedan Black
        new(
            vehicles[9].Id,
            (string)"LanosCertifiedStore/Vehicles/uhjtwo64n6dolzo2wymj",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527116/LanosCertifiedStore/Vehicles/uhjtwo64n6dolzo2wymj.jpg",
            true),
        new(
            vehicles[9].Id,
            (string)"LanosCertifiedStore/Vehicles/boblrcknalx6nfsegnwt",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527116/LanosCertifiedStore/Vehicles/boblrcknalx6nfsegnwt.jpg",
            false),
        new(
            vehicles[9].Id,
            (string)"LanosCertifiedStore/Vehicles/hr7ayufgd5qabparfmph",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527116/LanosCertifiedStore/Vehicles/hr7ayufgd5qabparfmph.jpg",
            false),
        new(
            vehicles[9].Id,
            (string)"LanosCertifiedStore/Vehicles/q1wfvcif3zlfeeyupklt",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527116/LanosCertifiedStore/Vehicles/q1wfvcif3zlfeeyupklt.jpg",
            false),
        new(
            vehicles[9].Id,
            (string)"LanosCertifiedStore/Vehicles/m0t7q445rsxn3mvuezqf",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527116/LanosCertifiedStore/Vehicles/m0t7q445rsxn3mvuezqf.jpg",
            false),
        new(
            vehicles[9].Id,
            (string)"LanosCertifiedStore/Vehicles/avdjatzkedxmun34rbsy",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527116/LanosCertifiedStore/Vehicles/avdjatzkedxmun34rbsy.jpg",
            false),
        // Mercedes-Benz C-Class Convertible Black
        new(
            vehicles[10].Id,
            (string)"LanosCertifiedStore/Vehicles/oa7k6bpoeiw1bitly9tu",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527924/LanosCertifiedStore/Vehicles/oa7k6bpoeiw1bitly9tu.jpg",
            true),
        new(
            vehicles[10].Id,
            (string)"LanosCertifiedStore/Vehicles/lisgev1kp2f47uje8smb",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527924/LanosCertifiedStore/Vehicles/lisgev1kp2f47uje8smb.jpg",
            false),
        new(
            vehicles[10].Id,
            (string)"LanosCertifiedStore/Vehicles/jt9yxzgiscfk4bv85psf",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527924/LanosCertifiedStore/Vehicles/jt9yxzgiscfk4bv85psf.jpg",
            false),
        new(
            vehicles[10].Id,
            (string)"LanosCertifiedStore/Vehicles/dtydenvxvfq9ek9t5ink",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708527924/LanosCertifiedStore/Vehicles/dtydenvxvfq9ek9t5ink.jpg",
            false),
        // Mercedes-Benz C-Class Wagon Silver
        new(
            vehicles[11].Id,
            (string)"LanosCertifiedStore/Vehicles/uzj6jgtawgbyargn8vnv",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708534533/LanosCertifiedStore/Vehicles/uzj6jgtawgbyargn8vnv.jpg",
            true),
        new(
            vehicles[11].Id,
            (string)"LanosCertifiedStore/Vehicles/w8b3szhvhx1tmzmyjsv6",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708534533/LanosCertifiedStore/Vehicles/w8b3szhvhx1tmzmyjsv6.jpg",
            false),
        new(
            vehicles[11].Id,
            (string)"LanosCertifiedStore/Vehicles/v4nzlyzyvgknqcesbgf2",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708534533/LanosCertifiedStore/Vehicles/v4nzlyzyvgknqcesbgf2.jpg",
            false),
        new(
            vehicles[11].Id,
            (string)"LanosCertifiedStore/Vehicles/qeixfh87rlbd1rfrcj1f",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708534533/LanosCertifiedStore/Vehicles/qeixfh87rlbd1rfrcj1f.jpg",
            false),
        // Mercedes-Benz C-Class Wagon Blue
        new(
            vehicles[12].Id,
            (string)"LanosCertifiedStore/Vehicles/sy2xa2bpwxw6nclt8tm9",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708536207/LanosCertifiedStore/Vehicles/sy2xa2bpwxw6nclt8tm9.jpg",
            true),
        new(
            vehicles[12].Id,
            (string)"LanosCertifiedStore/Vehicles/t3bp6xj2mwzujus8pqx2",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708536207/LanosCertifiedStore/Vehicles/t3bp6xj2mwzujus8pqx2.jpg",
            false),
        new(
            vehicles[12].Id,
            (string)"LanosCertifiedStore/Vehicles/lfqnmz7n8ps3azrtjfjo",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708536207/LanosCertifiedStore/Vehicles/lfqnmz7n8ps3azrtjfjo.jpg",
            false),
        new(
            vehicles[12].Id,
            (string)"LanosCertifiedStore/Vehicles/vd0h6bazstc0v996ywqb",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708536207/LanosCertifiedStore/Vehicles/vd0h6bazstc0v996ywqb.jpg",
            false),
        // Audi A6 Wagon Indigo
        new(
            vehicles[13].Id,
            (string)"LanosCertifiedStore/Vehicles/gsbmeqerr51p8nfkgppk",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542486/LanosCertifiedStore/Vehicles/gsbmeqerr51p8nfkgppk.jpg",
            true),
        new(
            vehicles[13].Id,
            (string)"LanosCertifiedStore/Vehicles/efrcrfdakx4mvdwco77z",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542486/LanosCertifiedStore/Vehicles/efrcrfdakx4mvdwco77z.jpg",
            false),
        new(
            vehicles[13].Id,
            (string)"LanosCertifiedStore/Vehicles/cvqqwhntruk2pg4v4yrc",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542486/LanosCertifiedStore/Vehicles/cvqqwhntruk2pg4v4yrc.jpg",
            false),
        new(
            vehicles[13].Id,
            (string)"LanosCertifiedStore/Vehicles/i3stkvvfctvdgkfsfb40",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542486/LanosCertifiedStore/Vehicles/i3stkvvfctvdgkfsfb40.jpg",
            false),
        // Audi A6 Wagon White
        new(
            vehicles[14].Id,
            (string)"LanosCertifiedStore/Vehicles/acothnpgzuu0gynptpca",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542959/LanosCertifiedStore/Vehicles/acothnpgzuu0gynptpca.jpg",
            true),
        new(
            vehicles[14].Id,
            (string)"LanosCertifiedStore/Vehicles/dv4x0wscscv9ifoiafaa",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542959/LanosCertifiedStore/Vehicles/dv4x0wscscv9ifoiafaa.jpg",
            false),
        new(
            vehicles[14].Id,
            (string)"LanosCertifiedStore/Vehicles/qagtaybqyhop9cgyrjfb",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542959/LanosCertifiedStore/Vehicles/qagtaybqyhop9cgyrjfb.jpg",
            false),
        new(
            vehicles[14].Id,
            (string)"LanosCertifiedStore/Vehicles/cj8mp4gtfo85efmovifk",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708542959/LanosCertifiedStore/Vehicles/cj8mp4gtfo85efmovifk.jpg",
            false),
        // Audi A6 Wagon Red
        new(
            vehicles[15].Id,
            (string)"LanosCertifiedStore/Vehicles/xkwpjcjjrnxermtpwyyr",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586002/LanosCertifiedStore/Vehicles/xkwpjcjjrnxermtpwyyr.jpg",
            true),
        new(
            vehicles[15].Id,
            (string)"LanosCertifiedStore/Vehicles/irty2dbdmuzudlg6olmq",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586002/LanosCertifiedStore/Vehicles/irty2dbdmuzudlg6olmq.jpg",
            false),
        new(
            vehicles[15].Id,
            (string)"LanosCertifiedStore/Vehicles/nlipbyqzgsuws7c5qh6i",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586002/LanosCertifiedStore/Vehicles/nlipbyqzgsuws7c5qh6i.jpg",
            false),
        new(
            vehicles[15].Id,
            (string)"LanosCertifiedStore/Vehicles/bx6rez4yomcfnclkp8cb",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586002/LanosCertifiedStore/Vehicles/bx6rez4yomcfnclkp8cb.jpg",
            false),
        new(
            vehicles[15].Id,
            (string)"LanosCertifiedStore/Vehicles/uzl7wdzodncum9urabqm",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586002/LanosCertifiedStore/Vehicles/uzl7wdzodncum9urabqm.jpg",
            false),
        // Audi A6 Sedan White
        new(
            vehicles[16].Id,
            (string)"LanosCertifiedStore/Vehicles/w1ttimm7xmpislznydhr",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586956/LanosCertifiedStore/Vehicles/w1ttimm7xmpislznydhr.jpg",
            true),
        new(
            vehicles[16].Id,
            (string)"LanosCertifiedStore/Vehicles/synzeo6hmjxqoghsn7wq",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586956/LanosCertifiedStore/Vehicles/synzeo6hmjxqoghsn7wq.jpg",
            false),
        new(
            vehicles[16].Id,
            (string)"LanosCertifiedStore/Vehicles/m0szsg9m8lyxsfig85p9",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586956/LanosCertifiedStore/Vehicles/m0szsg9m8lyxsfig85p9.jpg",
            false),
        new(
            vehicles[16].Id,
            (string)"LanosCertifiedStore/Vehicles/ryjb7fqhgszt60jp8wft",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708586956/LanosCertifiedStore/Vehicles/ryjb7fqhgszt60jp8wft.jpg",
            false),
        // Hyundai Sonata Sedan Gray
        new(
            vehicles[17].Id,
            (string)"LanosCertifiedStore/Vehicles/zkhogmt5magvlwdgk2xr",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/zkhogmt5magvlwdgk2xr.jpg",
            true),
        new(
            vehicles[17].Id,
            (string)"LanosCertifiedStore/Vehicles/zhdgh4ejkei7fnscenz5",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/zhdgh4ejkei7fnscenz5.jpg",
            false),
        new(
            vehicles[17].Id,
            (string)"LanosCertifiedStore/Vehicles/jseydxanpn9t9mhaa8x5",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/jseydxanpn9t9mhaa8x5.jpg",
            false),
        // Hyundai Sonata Sedan Red
        new(
            vehicles[18].Id,
            (string)"LanosCertifiedStore/Vehicles/k79qqqvbttceaehujhup",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/k79qqqvbttceaehujhup.jpg",
            true),
        new(
            vehicles[18].Id,
            (string)"LanosCertifiedStore/Vehicles/japgswl2aythbwlqsx4w",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/japgswl2aythbwlqsx4w.jpg",
            false),
        new(
            vehicles[18].Id,
            (string)"LanosCertifiedStore/Vehicles/xnpfpy1b5wxfgvmbk2bc",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/xnpfpy1b5wxfgvmbk2bc.jpg",
            false),
        // Hyundai Sonata Sedan White
        new(
            vehicles[19].Id,
            (string)"LanosCertifiedStore/Vehicles/qjdz6cu373p4uflkncoo",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/qjdz6cu373p4uflkncoo.jpg",
            true),
        new(
            vehicles[19].Id,
            (string)"LanosCertifiedStore/Vehicles/njusrnhl9xxyxlnol3dx",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/njusrnhl9xxyxlnol3dx.jpg",
            false),
        new(
            vehicles[19].Id,
            (string)"LanosCertifiedStore/Vehicles/lzzqy88trooi1gfmapks",
            (string)"https://res.cloudinary.com/dmdnphybu/image/upload/v1708587741/LanosCertifiedStore/Vehicles/lzzqy88trooi1gfmapks.jpg",
            false),
    ];
}
