using Persistence.DataModels.VehicleRelated.TypeRelated;
using Persistence.QueryBuilder.Common;

namespace Persistence.Repositories.TypeRelated.VehicleEngineTypeRelated.QueryBuilderRelated.Common.Classes;

internal class VehicleEngineTypeSortingSettings : BaseSortingSettings<VehicleEngineTypeDataModel>;